In [1]:
# Create a Table For Nav_History

In [2]:
import pandas as pd
import plotly.express as px

nav = pd.read_csv("C:/MutualFundProject/data/raw/02_nav_history.csv")

nav.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [3]:
fund_master = pd.read_csv("C:/MutualFundProject/data/raw/01_fund_master.csv")

print(fund_master.columns)

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [4]:
nav = nav.merge(
    fund_master[["amfi_code", "scheme_name"]],
    on="amfi_code",
    how="left"
)

In [5]:
print(nav["scheme_name"].isna().sum())

0

In [6]:
print(nav.columns)

Index(['amfi_code', 'date', 'nav', 'scheme_name'], dtype='str')

In [7]:
nav.to_csv(
    "c:/MutualFundProject/data/processed/cleaned_dataset/02_nav_history.csv",
    index=False
)

In [8]:
## Create Table For Aum_History

In [9]:
aum = pd.read_csv("c:/MutualFundProject/data/raw/03_fund_aum.csv")

aum.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [10]:
aum.rename(
    columns={"aum_crore": "aum"},
    inplace=True
)

In [11]:
aum.shape

(90, 5)

In [12]:
aum.dtypes

date                  str
fund_house            str
aum_lakh_crore    float64
aum                 int64
num_schemes         int64
dtype: object

In [13]:
aum["date"] = pd.to_datetime(aum["date"])

In [14]:
aum["year"] = (aum["date"].dt.year)

In [15]:
aum_history = (
    aum
    .sort_values(["fund_house", "date"])
    .groupby(["fund_house", "year"])
    .tail(1)
)

In [16]:
aum_history = aum_history[
    ["fund_house", "year", "aum"]
]

In [17]:
aum_history.head()

                  fund_house  year     aum
15  Aditya Birla Sun Life MF  2022  285000
35  Aditya Birla Sun Life MF  2023  308000
65  Aditya Birla Sun Life MF  2024  384000
85  Aditya Birla Sun Life MF  2025  460000
16          Axis Mutual Fund  2022  240000

In [18]:
import os

os.makedirs("c:/MutualFundProject/data/processed/cleaned_dataset", exist_ok=True)

In [19]:
aum_history.to_csv(
    "c:/MutualFundProject/data/processed/cleaned_dataset/03_aum_history.csv",
    index=False
)

In [20]:
# Investor_demographics Table

In [21]:
import pandas as pd

df = pd.read_csv("C:/MutualFundProject/data/raw/08_investor_transactions.csv")

print(df.shape)
print(df.head())
print(df.columns)
print(df.dtypes)

(32778, 13)
  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending
Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

In [22]:
sip_df = df.rename(
    columns={'amount_inr': 'sip_amount'}
)

In [23]:
sip_amount_table = sip_df[
    ['investor_id', 'age_group', 'gender', 'sip_amount']
].copy()
print(sip_amount_table.head())

  investor_id age_group  gender  sip_amount
0   INV003054       56+  Female        1834
1   INV002952     18-25    Male      392882
2   INV003420     36-45    Male         912
3   INV003436     36-45  Female        1102
4   INV004691     26-35    Male        8682

In [24]:
print(sip_df[['investor_id', 'age_group', 'gender', 'sip_amount']].isnull().sum())

investor_id    0
age_group      0
gender         0
sip_amount     0
dtype: int64

In [25]:
print(df['age_group'].value_counts().sort_index())

age_group
18-25     4916
26-35    13463
36-45     8146
46-55     3779
56+       2474
Name: count, dtype: int64

In [26]:
age_counts = df['age_group'].value_counts().sort_index()

print(age_counts)

age_group
18-25     4916
26-35    13463
36-45     8146
46-55     3779
56+       2474
Name: count, dtype: int64

In [27]:
investor_df = sip_df.drop(columns=["transaction_date","amfi_code","state","city","city_tier","annual_income_lakh","payment_mode","kyc_status"])
print(investor_df.head())

  investor_id transaction_type  sip_amount age_group  gender
0   INV003054              SIP        1834       56+  Female
1   INV002952       Redemption      392882     18-25    Male
2   INV003420              SIP         912     36-45    Male
3   INV003436              SIP        1102     36-45  Female
4   INV004691          Lumpsum        8682     26-35    Male

In [28]:
investor_df.to_csv(
    "C:/MutualFundProject/data/processed/cleaned_dataset/08_investor_transactions.csv",
     index=False
)
print("file saved sucessfully!")

file saved sucessfully!

In [29]:
investor_df

      investor_id transaction_type  sip_amount age_group  gender
0       INV003054              SIP        1834       56+  Female
1       INV002952       Redemption      392882     18-25    Male
2       INV003420              SIP         912     36-45    Male
3       INV003436              SIP        1102     36-45  Female
4       INV004691          Lumpsum        8682     26-35    Male
...           ...              ...         ...       ...     ...
32773   INV003340          Lumpsum      168029     26-35    Male
32774   INV001838              SIP        2175     46-55    Male
32775   INV000074              SIP       25998     26-35  Female
32776   INV002929              SIP         459     26-35    Male
32777   INV001852       Redemption      226721     26-35    Male

[32778 rows x 5 columns]

In [30]:
df

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32773,INV003340,2025-05-30,101207,Lumpsum,168029,Madhya Pradesh,Indore,T30,26-35,Male,22.5,Net Banking,Verified
32774,INV001838,2025-05-30,119093,SIP,2175,Uttar Pradesh,Kanpur,B30,46-55,Male,27.6,Mandate,Verified
32775,INV000074,2025-05-30,120504,SIP,25998,Rajasthan,Jaipur,T30,26-35,Female,8.4,UPI,Verified
32776,INV002929,2025-05-30,148568,SIP,459,West Bengal,Kolkata,T30,26-35,Male,13.0,Mandate,Verified
32777,INV001852,2025-05-30,118633,Redemption,226721,Telangana,Hyderabad,T30,26-35,Male,21.7,Cheque,Verified

In [31]:
investor_df = investor_df.merge(df[['investor_id','state','city_tier']], on='investor_id')

In [32]:
print(investor_df)

       investor_id transaction_type  sip_amount age_group  gender      state  \
0        INV003054              SIP        1834       56+  Female  Telangana
1        INV003054              SIP        1834       56+  Female  Telangana
2        INV003054              SIP        1834       56+  Female  Telangana
3        INV003054              SIP        1834       56+  Female  Telangana
4        INV003054              SIP        1834       56+  Female  Telangana
...            ...              ...         ...       ...     ...        ...
274427   INV001852       Redemption      226721     26-35    Male  Telangana
274428   INV001852       Redemption      226721     26-35    Male  Telangana
274429   INV001852       Redemption      226721     26-35    Male  Telangana
274430   INV001852       Redemption      226721     26-35    Male  Telangana
274431   INV001852       Redemption      226721     26-35    Male  Telangana

       city_tier
0            T30
1            T30
2            T30
3            T30
4            T30
...          ...
274427       T30
274428       T30
274429       T30
274430       T30
274431       T30

[274432 rows x 7 columns]

In [33]:
investor_df.to_csv(
    "C:/MutualFundProject/data/processed/cleaned_dataset/08_investor_demographics.csv",
     index=False
)
print("file saved sucessfully!")

file saved sucessfully!

In [34]:
# Portfolio_Holdings_table

In [35]:
import pandas as pd

holdings = pd.read_csv("C:/MutualFundProject/data/raw/09_portfolio_holdings.csv")
fund_master = pd.read_csv("C:/MutualFundProject/data/raw/01_fund_master.csv")

print(holdings.columns)
print(fund_master.columns)

Index(['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct',
       'market_value_cr', 'current_price_inr', 'portfolio_date'],
      dtype='str')
Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [36]:
holdings = holdings.merge(
    fund_master[
        ['amfi_code', 'scheme_name', 'fund_house']
    ],
    on='amfi_code',
    how='left'
)

In [37]:
print(holdings.head())

   amfi_code stock_symbol                stock_name       sector  weight_pct  \
0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85
1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19
2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90
3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76
4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25

   market_value_cr  current_price_inr portfolio_date  \
0           737.09            6011.08     2025-12-31
1            88.97            1074.65     2025-12-31
2           208.45            5964.59     2025-12-31
3           161.32            3748.82     2025-12-31
4           725.90            1321.45     2025-12-31

                                 scheme_name       fund_house
0  SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1  SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
2  SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
3  SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
4  SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund

In [38]:
holdings_df = holdings.rename(columns={"fund_house":"fund_type","weight_pct":"weight"})

In [39]:
holdings_df.to_csv(
    "C:/MutualFundProject/data/processed/cleaned_dataset/09_holdings_portfolio.csv",
     index=False
)
print("file saved sucessfully!")

file saved sucessfully!

In [40]:
# NIFTY 50 Table

In [41]:
import pandas as pd

df = pd.read_csv("C:/MutualFundProject/data/raw/10_benchmark_indices.csv")

# Filter only NIFTY50
nifty50 = df[
    df["index_name"].astype(str).str.strip().str.upper() == "NIFTY50"
].copy()

# Print NIFTY50 data
print(nifty50)

            date index_name  close_value
0     2022-01-03    NIFTY50     17492.79
1     2022-01-04    NIFTY50     17689.64
2     2022-01-05    NIFTY50     17835.05
3     2022-01-06    NIFTY50     17878.51
4     2022-01-07    NIFTY50     17759.15
...          ...        ...          ...
1145  2026-05-25    NIFTY50     18186.57
1146  2026-05-26    NIFTY50     18418.36
1147  2026-05-27    NIFTY50     18523.57
1148  2026-05-28    NIFTY50     18421.08
1149  2026-05-29    NIFTY50     18517.65

[1150 rows x 3 columns]

In [42]:
nifty50['daily_return'] = (
    nifty50['close_value'] / nifty50['close_value'].shift(1)
) - 1

In [43]:
nifty50['daily_return'] = nifty50['close_value'].pct_change()

In [44]:
print(nifty50.head())

         date index_name  close_value  daily_return
0  2022-01-03    NIFTY50     17492.79           NaN
1  2022-01-04    NIFTY50     17689.64      0.011253
2  2022-01-05    NIFTY50     17835.05      0.008220
3  2022-01-06    NIFTY50     17878.51      0.002437
4  2022-01-07    NIFTY50     17759.15     -0.006676

In [45]:
nifty50_returns = nifty50[['date', 'close_value', 'daily_return']].copy()

nifty50_returns = nifty50_returns.rename(
    columns={'daily_return': 'nifty50_return'}
)

In [46]:
print(nifty50_returns.head())

         date  close_value  nifty50_return
0  2022-01-03     17492.79             NaN
1  2022-01-04     17689.64        0.011253
2  2022-01-05     17835.05        0.008220
3  2022-01-06     17878.51        0.002437
4  2022-01-07     17759.15       -0.006676

In [47]:
# Save to CSV
nifty50_returns.to_csv("C:/MutualFundProject/data/raw/nifty50.csv", index=False)

In [48]:
## Nifty 100 Table

In [49]:
import pandas as pd

df = pd.read_csv("C:/MutualFundProject/data/raw/10_benchmark_indices.csv")

# Filter only NIFTY50
nifty100 = df[
    df["index_name"].astype(str).str.strip().str.upper() == "NIFTY100"
].copy()

# Print NIFTY50 data
print(nifty100)

# Save to CSV
## nifty50.to_csv("nifty50_only.csv", index=False)

            date index_name  close_value
1150  2022-01-03   NIFTY100     17778.24
1151  2022-01-04   NIFTY100     17537.52
1152  2022-01-05   NIFTY100     17607.73
1153  2022-01-06   NIFTY100     17556.05
1154  2022-01-07   NIFTY100     17664.02
...          ...        ...          ...
2295  2026-05-25   NIFTY100     19245.64
2296  2026-05-26   NIFTY100     19228.08
2297  2026-05-27   NIFTY100     19489.24
2298  2026-05-28   NIFTY100     19677.97
2299  2026-05-29   NIFTY100     19696.29

[1150 rows x 3 columns]

In [50]:
nifty100['daily_return'] = (
    nifty100['close_value'] / nifty50['close_value'].shift(1)
) - 1

In [51]:
nifty100['daily_return'] = nifty100['close_value'].pct_change()

In [52]:
print(nifty100.head())

            date index_name  close_value  daily_return
1150  2022-01-03   NIFTY100     17778.24           NaN
1151  2022-01-04   NIFTY100     17537.52     -0.013540
1152  2022-01-05   NIFTY100     17607.73      0.004003
1153  2022-01-06   NIFTY100     17556.05     -0.002935
1154  2022-01-07   NIFTY100     17664.02      0.006150

In [53]:
nifty100_returns = nifty100[['date', 'close_value', 'daily_return']].copy()

nifty100_returns = nifty100_returns.rename(
    columns={'daily_return': 'nifty50_return'}
)

In [54]:
# Save to CSV
nifty100_returns.to_csv("C:/MutualFundProject/data/raw/nifty100.csv", index=False)